### ISSUE TITLE
Error while training

### ISSUE THREAD

**Issue by oliver0922** [monchhichizzq/Mobilenet-SSD-Kitti-Object-Detection#1]
Hi thank you for your kind github.

I'm trying to train KITTI dataset using your code.

When I compile the train.py in Google COLAB an error like below occured. 

Would you please help me?

WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/array_ops.py:5049: calling gather (from tensorflow.python.ops.array_ops) with validate_indices is deprecated and will be removed in a future version.
Instructions for updating:
The `validate_indices` argument has no effect. Indices are always validated on CPU and never validated on GPU.
Traceback (most recent call last):
  File "train.py", line 107, in <module>
    callbacks=[checkpoint, reduce_lr, early_stopping])
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py", line 1183, in fit
    tmp_logs = self.train_function(iterator)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/def_function.py", line 889, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/def_function.py", line 933, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/def_function.py", line 764, in _initialize
    *args, **kwds))
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py", line 3050, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py", line 3444, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py", line 3289, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/func_graph.py", line 999, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/def_function.py", line 672, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/func_graph.py", line 986, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py:855 train_function  *
        return step_function(self, iterator)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py:845 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/distribute_lib.py:1285 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/distribute_lib.py:2833 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/distribute_lib.py:3608 _call_for_each_replica
        return fn(*args, **kwargs)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py:838 run_step  **
        outputs = model.train_step(data)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py:797 train_step
        y, y_pred, sample_weight, regularization_losses=self.losses)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/compile_utils.py:204 __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/losses.py:157 __call__
        losses, sample_weight, reduction=self._get_reduction())
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/utils/losses_utils.py:301 compute_weighted_loss
        losses = ops.convert_to_tensor_v2_with_dispatch(losses)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py:206 wrapper
        return target(*args, **kwargs)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py:1431 convert_to_tensor_v2_with_dispatch
        value, dtype=dtype, dtype_hint=dtype_hint, name=name)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py:1441 convert_to_tensor_v2
        as_ref=False)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/profiler/trace.py:163 wrapped
        return func(*args, **kwargs)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py:1566 convert_to_tensor
        ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/array_ops.py:1536 _autopacking_conversion_function
        return _autopacking_helper(v, dtype, name or "packed")
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/array_ops.py:1472 _autopacking_helper
        return gen_array_ops.pack(elems_as_tensors, name=scope)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/gen_array_ops.py:6418 pack
        "Pack", values=values, axis=axis, name=name)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/op_def_library.py:750 _apply_op_helper
        attrs=attr_protos, op_def=op_def)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/func_graph.py:601 _create_op_internal
        compute_device)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py:3565 _create_op_internal
        op_def=op_def)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py:2042 __init__
        control_input_ops, op_def)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py:1883 _create_c_op
        raise ValueError(str(e))

    ValueError: Shapes must be equal rank, but are 0 and 2
    	From merging shape 0 with other shapes. for '{{node compute_loss/weighted_loss/packed}} = Pack[N=3, T=DT_FLOAT, axis=0](compute_loss/add_2, compute_loss/Neg, compute_loss/Sum_1)' with input shapes: [], [?,9646], [?,9646].

**Comment by oliver0922** [comment]
I think the error occured because of weight file.

Where can I download essay_mobilenet_ssd_weights.h5?

thx

**Comment by oliver0922** [comment]
Sorry for irritating.

Would you please essay_mobilenet_ssd_weights.h5 file? to my email(oliver0922@kookmin.ac.kr)?

I don't use bidu sorry.

thx

**Comment by monchhichizzq** [comment]
Hello,

Sure. essay_mobilenet_ssd_weights.h5 is the initialization weights, you
want the trained weights or this?

Best,
Zeqi


InJae Lee ***@***.***> 于2021年6月12日周六 下午10:43写道：

**Comment by monchhichizzq** [comment]
I think your error comes from running train_eager.py, it's better to run train.py

**Comment by monchhichizzq** [comment]
> Sorry for irritating.
> 
> Would you please essay_mobilenet_ssd_weights.h5 file? to my email([oliver0922@kookmin.ac.kr](mailto:oliver0922@kookmin.ac.kr))?
> 
> I don't use bidu sorry.
> 
> thx

I think your error comes from running train_eager.py, it's better to run train.py

**Comment by oliver0922** [comment]
> > Sorry for irritating.
> > Would you please essay_mobilenet_ssd_weights.h5 file? to my email([oliver0922@kookmin.ac.kr](mailto:oliver0922@kookmin.ac.kr))?
> > I don't use bidu sorry.
> > thx
> 
> I think your error comes from running train_eager.py, it's better to run train.py

Thanks for your reply.

However I don't using tran_eager.py. The error comes when I run the train.py

The error messages are below


WARNING:tensorflow:Skipping loading of weights for layer conv4_3_norm_mbox_conf due to mismatch in shape ((3, 3, 256, 54) vs (84, 512, 3, 3)).
WARNING:tensorflow:Skipping loading of weights for layer conv4_3_norm_mbox_conf due to mismatch in shape ((54,) vs (84,)).
WARNING:tensorflow:Skipping loading of weights for layer fc7_mbox_conf due to mismatch in shape ((3, 3, 1024, 54) vs (126, 1024, 3, 3)).
WARNING:tensorflow:Skipping loading of weights for layer fc7_mbox_conf due to mismatch in shape ((54,) vs (126,)).
WARNING:tensorflow:Skipping loading of weights for layer conv6_2_mbox_conf due to mismatch in shape ((3, 3, 512, 54) vs (126, 512, 3, 3)).
WARNING:tensorflow:Skipping loading of weights for layer conv6_2_mbox_conf due to mismatch in shape ((54,) vs (126,)).
WARNING:tensorflow:Skipping loading of weights for layer conv7_2_mbox_conf due to mismatch in shape ((3, 3, 256, 54) vs (126, 256, 3, 3)).
WARNING:tensorflow:Skipping loading of weights for layer conv7_2_mbox_conf due to mismatch in shape ((54,) vs (126,)).
WARNING:tensorflow:Skipping loading of weights for layer conv8_2_mbox_conf due to mismatch in shape ((3, 3, 256, 54) vs (126, 256, 3, 3)).
WARNING:tensorflow:Skipping loading of weights for layer conv8_2_mbox_conf due to mismatch in shape ((54,) vs (126,)).
WARNING:tensorflow:Skipping loading of weights for layer conv9_2_mbox_conf due to mismatch in shape ((3, 3, 128, 36) vs (126, 128, 3, 3)).
WARNING:tensorflow:Skipping loading of weights for layer conv9_2_mbox_conf due to mismatch in shape ((36,) vs (126,)).
WARNING:tensorflow:Skipping loading of weights for layer conv4_3_norm_mbox_loc due to mismatch in shape ((3, 3, 256, 24) vs (16, 512, 3, 3)).
WARNING:tensorflow:Skipping loading of weights for layer conv4_3_norm_mbox_loc due to mismatch in shape ((24,) vs (16,)).
WARNING:tensorflow:Skipping loading of weights for layer conv9_2_mbox_loc due to mismatch in shape ((3, 3, 128, 16) vs (24, 128, 3, 3)).
WARNING:tensorflow:Skipping loading of weights for layer conv9_2_mbox_loc due to mismatch in shape ((16,) vs (24,)).
/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:375: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  "The `lr` argument is deprecated, use `learning_rate` instead.")
Epoch 1/1000
(None, 20, 60, 256)
(None, 10, 30, 1024)
(None, 5, 15, 512)
(None, 3, 8, 256)
(None, 2, 4, 256)
(None, 1, 1, 128)
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/array_ops.py:5049: calling gather (from tensorflow.python.ops.array_ops) with validate_indices is deprecated and will be removed in a future version.
Instructions for updating:
The `validate_indices` argument has no effect. Indices are always validated on CPU and never validated on GPU.
Traceback (most recent call last):
  File "train.py", line 107, in <module>
    callbacks=[checkpoint, reduce_lr, early_stopping])
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py", line 1183, in fit
    tmp_logs = self.train_function(iterator)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/def_function.py", line 889, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/def_function.py", line 933, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/def_function.py", line 764, in _initialize
    *args, **kwds))
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py", line 3050, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py", line 3444, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py", line 3289, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/func_graph.py", line 999, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/def_function.py", line 672, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/func_graph.py", line 986, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py:855 train_function  *
        return step_function(self, iterator)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py:845 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/distribute_lib.py:1285 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/distribute_lib.py:2833 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/distribute_lib.py:3608 _call_for_each_replica
        return fn(*args, **kwargs)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py:838 run_step  **
        outputs = model.train_step(data)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py:797 train_step
        y, y_pred, sample_weight, regularization_losses=self.losses)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/compile_utils.py:204 __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/losses.py:157 __call__
        losses, sample_weight, reduction=self._get_reduction())
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/utils/losses_utils.py:301 compute_weighted_loss
        losses = ops.convert_to_tensor_v2_with_dispatch(losses)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py:206 wrapper
        return target(*args, **kwargs)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py:1431 convert_to_tensor_v2_with_dispatch
        value, dtype=dtype, dtype_hint=dtype_hint, name=name)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py:1441 convert_to_tensor_v2
        as_ref=False)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/profiler/trace.py:163 wrapped
        return func(*args, **kwargs)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py:1566 convert_to_tensor
        ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/array_ops.py:1536 _autopacking_conversion_function
        return _autopacking_helper(v, dtype, name or "packed")
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/array_ops.py:1472 _autopacking_helper
        return gen_array_ops.pack(elems_as_tensors, name=scope)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/gen_array_ops.py:6418 pack
        "Pack", values=values, axis=axis, name=name)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/op_def_library.py:750 _apply_op_helper
        attrs=attr_protos, op_def=op_def)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/func_graph.py:601 _create_op_internal
        compute_device)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py:3565 _create_op_internal
        op_def=op_def)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py:2042 __init__
        control_input_ops, op_def)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py:1883 _create_c_op
        raise ValueError(str(e))

    ValueError: Shapes must be equal rank, but are 0 and 2
    	From merging shape 0 with other shapes. for '{{node compute_loss/weighted_loss/packed}} = Pack[N=3, T=DT_FLOAT, axis=0](compute_loss/add_2, compute_loss/Neg, compute_loss/Sum_1)' with input shapes: [], [?,9646], [?,9646].
